Models/GridLayout.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nop.Plugin.Misc.GridLayout.Models
{
    /// <summary>
    /// Layout
    /// </summary>
    public class Layout
    {
        public Layout() { }
        public int ActiveOccurances { get; set; }
        public GridGroup GridGroup { get; set; }    
    }
}

ViewModels/LayoutViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Nop.Plugin.Misc.GridLayout.Models;

namespace Nop.Plugin.Misc.GridLayout.ViewModels
{
    public class LayoutViewModel
    {
        public LayoutViewModel()
        {
          
        }

        /// <summary>
        /// Grid Group
        /// </summary>
        public GridGroup GridGroup { get; set; }

        /// <summary>
        /// Create Grid Item
        /// </summary>
        public GridItem CreateGridItem { get; set; }
    }
}

Controllers/GridLayoutController.cs
using System.Web.Mvc;
using Nop.Web.Framework.Controllers;
using Nop.Plugin.Misc.GridLayout.Models;
using Nop.Core.Data;
using Nop.Services.Catalog;
using Nop.Plugin.Misc.GridLayout.ViewModels;
using System.Collections.Generic;
using Nop.Core.Domain.Catalog;
using System.Linq;
using Nop.Services.Configuration;
using Nop.Services.Media;
using Nop.Web.Models.Catalog;
using Nop.Web.Models.Media;
using Nop.Core.Domain.Media;
using Nop.Services.Localization;
using Telerik.Web.Mvc;
using Nop.Admin.Models.Catalog;
using Nop.Services.Security;
using Nop.Core;
using Nop.Core.Domain;
using Nop.Core.Domain.Common;
using Nop.Admin;
using Nop.Web.Framework;
using System;
using Nop.Plugin.Misc.GridLayout.Services;

namespace Nop.Plugin.Misc.GridLayout.Controllers
{
    /// <summary>
    /// TO DO : Split out into a category image manager controller and a product image controller
    ///         Create a service to deal with data collection and aggregation rather than doing the work in the controller.
    /// </summary>
    public class GridLayoutController : Controller
    {
        private readonly IGridLayoutService _gridLayoutService;
        private readonly ICategoryService _categoryService;
        private readonly GridLayoutSettings _gridLayoutSettings;
        private readonly ISettingService _settingService;
        private readonly IPictureService _pictureService;
        private readonly IProductService _productService;
        private readonly MediaSettings _mediaSettings;
        private readonly ILocalizationService _localizationService;
        private readonly IWorkContext _workContext;
        private readonly IPermissionService _permissionService;
        private readonly AdminAreaSettings _adminAreaSettings;
        private readonly string _entityType = "category";

        public GridLayoutController(IGridLayoutService gridLayoutService, ICategoryService categoryService, GridLayoutSettings gridLayoutSettings, ISettingService settingService, IPictureService pictureService, IProductService productService, MediaSettings mediaSettings, ILocalizationService localizationService, IPermissionService permissionService, IWorkContext workContext, AdminAreaSettings adminAreaSettings)
        {
            _gridLayoutService = gridLayoutService;
            _gridLayoutSettings = gridLayoutSettings;
            _categoryService = categoryService;
            _settingService = settingService;
            _pictureService = pictureService;
            _productService = productService;
            _mediaSettings = mediaSettings;
          
            _localizationService = localizationService;
            _workContext = workContext;
            _permissionService = permissionService;
            _adminAreaSettings = adminAreaSettings;
        }

        [AdminAuthorize]
        public ActionResult Configure()
        {
            var model = _gridLayoutSettings;
            return View("Nop.Plugin.Misc.GridLayout.Views.MiscGridLayout.Configure", model);
        }

        [AdminAuthorize]
        [HttpPost]
        public void _Configure(GridLayoutSettings formCollection)
        {
           // Set properties here - add to later
            _settingService.SaveSetting(_gridLayoutSettings);
        }

        #region Index View

        [AdminAuthorize]
        [HttpGet]
        public ActionResult Index()
        {
            return View("Nop.Plugin.Misc.GridLayout.Views.MiscGridLayout.Index");
        }

        #endregion

        #region Grid Layout / Group

        [HttpPost]
        [AdminAuthorize]
        public JsonResult _GetGridLayout(int gridGroupId)
        {
            if(gridGroupId > 0)
            {
                return Json(this._gridLayoutService.GetGridGroupById(gridGroupId));
            }

            return Json(String.Empty);
        }


        /// <summary>
        /// Get Grid Items
        /// </summary>
        /// <param name="gridGroupId"></param>
        /// <returns></returns>
        [GridAction]
        [AdminAuthorize]
        public JsonResult _GetAllGridGroups()
        {
            return Json(this._gridLayoutService.GetAllGridGroups().OrderBy(x=>x.CreatedOn).ToList());
        }


        [AdminAuthorize]
        [HttpGet]
        public ActionResult ManageLayout(int? id)
        {
            LayoutViewModel model = new LayoutViewModel();
            model.GridGroup = new GridGroup();
            model.CreateGridItem = new GridItem(id);

            if (ModelState.IsValid)
            {
                if (id.HasValue)
                {
                    GridGroup gridGroup = this._gridLayoutService.GetGridGroupById(id.Value);
                    model.CreateGridItem.GridGroupId = gridGroup.Id;
                    model.GridGroup = gridGroup;
                }           
            }
            return View("Nop.Plugin.Misc.GridLayout.Views.MiscGridLayout.Layout", model);
        }

        /// <summary>
        /// Update Layout, this should update all of the child objects as well
        /// check..
        /// </summary>
        /// <param name="gridGroupViewModel"></param>
        /// <returns></returns>
        [AdminAuthorize]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult UpsertLayout(LayoutViewModel layoutViewModel)
        {
            if (ModelState.IsValid)
            {
                if (layoutViewModel.GridGroup.Id > 0)
                {
                    // It exists so lets update it 
                    this._gridLayoutService.UpdateGridGroup(layoutViewModel.GridGroup);
                }
                else 
                {
                    // It does not exist so lets create it.
                    this._gridLayoutService.CreateGridGroup(layoutViewModel.GridGroup);
                }
            }

            // set the grid item on the model again.
            layoutViewModel.CreateGridItem = new GridItem(layoutViewModel.GridGroup.Id);
            return View("Nop.Plugin.Misc.GridLayout.Views.MiscGridLayout.Layout", layoutViewModel);
        }

        /// <summary>
        /// Delete Layout
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AdminAuthorize]
        [HttpPost]
        public ActionResult DeleteLayout(int? id)
        {
            if (id.HasValue)
            {
                this._gridLayoutService.DeleteGridGroup(id.Value);
            }

            // Redirect to the main index page after deletion, check this does not need the full path!
            return RedirectToAction("Index");        
        }

        /// <summary>
        /// Delete Layout
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AdminAuthorize]
        [HttpGet]
        public ActionResult PreviewLayout(int gridGroupId)
        {
            GridGroup model = new GridGroup();

            if (gridGroupId > 0)
            {
                model = this._gridLayoutService.GetGridGroupById(gridGroupId);
            }

            return View("Nop.Plugin.Misc.GridLayout.Views.MiscGridLayout.PreviewLayout", model);
        }

        #region Return Partial View of a rendered grid layout

        /// <summary>
        /// Grid Layout
        /// </summary>
        /// <param name="entityId"></param>
        /// <returns></returns>
        public ViewResult _GridLayouts(int entityId)
        {
            IList<GridGroup> model = new List<GridGroup>();

            if (entityId > 0 && !String.IsNullOrEmpty(_entityType))
            {
                model = _gridLayoutService.GetGridGroups(entityId, _entityType);
            }

            return View("Nop.Plugin.Misc.GridLayout.Views.MiscGridLayout._GridLayout", model);
        }


        /// <summary>
        /// Get Grid Layouts By Params
        /// </summary>
        /// <param name="shortCode"></param>
        /// <returns></returns>
        public ViewResult _GridLayoutsByParams(string shortCode)
        {
            IList<GridGroup> model = new List<GridGroup>();

            if (!String.IsNullOrEmpty(shortCode))
            {
                model = this._gridLayoutService.GetGridGroupsByParams(shortCode);
            }

            return View("Nop.Plugin.Misc.GridLayout.Views.MiscGridLayout._GridLayout", model);
        }

        #region Has Grid Layout Action Methods

        /// <summary>
        /// Has Grid Layouts
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult HasGridLayouts(int? entityId)
        {
            bool hasAny = false;
            if(entityId.HasValue)
            {
                if ( entityId.Value > 0 && !String.IsNullOrEmpty(_entityType))
                {
                    hasAny = _gridLayoutService.HasGridGroups(entityId.Value, _entityType, true);
                }
            }

            ViewData["HasAny"] = hasAny;
            return View("Nop.Plugin.Misc.GridLayout.Views.MiscGridLayout.HasGridLayouts");
         
        }

        /// <summary>
        /// Has Grid Layouts
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult HasGridLayoutsByParams(string shortCode)
        {
            bool hasAny = false;

            if (!String.IsNullOrEmpty(shortCode))
            {
                hasAny = _gridLayoutService.HasGridGroupsByParams(shortCode);
            }

            ViewData["HasAny"] = hasAny;
            return View("Nop.Plugin.Misc.GridLayout.Views.MiscGridLayout.HasGridLayouts");
        }

        #endregion

        #endregion


        #region AJAX update methods

        #region GridGroup

        /// <summary>
        /// Delete Grid Item
        /// TODO : Add success / failure json text to return
        /// </summary>
        /// <param name="id"></param>
        [HttpPost]
        [AdminAuthorize]
        public void _DeleteGridGroup(int id)
        {

Views/MiscGridLayout/AddGridItem.cshtml
@model Nop.Plugin.Misc.GridLayout.Models.GridItem
@using Telerik.Web.Mvc.UI;

<div style="height:550px;width:800px;padding:20px;background:#fefefe;">
    <script type="text/javascript">

        function onGridItemInsertComplete() {
            // resets the recently changed items
            // $(':input').not(':button, :submit, :reset, :hidden').val('');
            $(".insert-grid-item-messages").html("");
            $(".insert-grid-item-messages").append("<strong>Grid item inserted</strong><br />");
            var grid = $("#GridItems").data("tGrid");
            grid.rebind();

        }

        function onGridItemUpdateFailure() {
            $(".insert-grid-item-messages").html("");
            $(".insert-grid-item-messages").append("<strong>There were issues inserting the grid item, please check the values are correct</strong><br />");
        }

        /*
        $(".updateGridItem").on("click", function () {
            var grid = $("#GridItems").data("tGrid");
            grid.rebind();
        });
        */

        // Return to the normal grid view.
        $(".insertGridItemCancel").on("click", function () {
            var grid = $("#GridItems").data("tGrid");
            grid.rebind();
        });

    </script>
    @using (Ajax.BeginForm("_InsertGridItem", "GridLayout", new AjaxOptions { OnSuccess = "onGridItemInsertComplete", OnFailure = "onGridItemInsertFailure" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <br />
        <h2>Insert Grid Item </h2>
        <div class="insert-grid-item-messages">

        </div>
        <table class="adminContent">
            <tr>
                <td class="adminTitle">

                    <!-- Hidden Id, not populate yet as we are new.-->
                    <input type="hidden" name="Id" value="@Model.Id" />

                    <!-- Hidden Group Id-->
                    <input type="hidden" name="GridGroupId" value="@Model.GridGroupId" />

                    <!-- Title -->
                    @Html.LabelFor(model => model.Title)
                </td>
                <td class="adminData">
                    @Html.EditorFor(model => model.Title)
                    @Html.ValidationMessageFor(model => model.Title)
                </td>
            </tr>

            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.URL)
                </td>
                <td class="adminData">
                    @Html.EditorFor(model => model.URL)
                    @Html.ValidationMessageFor(model => model.URL)
                </td>
            </tr>
            <tr>
            <td class="adminTitle">
                @Html.LabelFor(model => model.ItemTypeId)
            </td>
            <td class="adminData">
                @* Look to bring this back on the view model, with more time! *@
                <select id="ItemTypeId" name="ItemTypeId">
                    @foreach (Nop.Plugin.Misc.GridLayout.Models.GridItemType itemType in Enum.GetValues(typeof(Nop.Plugin.Misc.GridLayout.Models.GridItemType)))
                    {
                        int itemTypeId = (int)itemType;
                        if (itemTypeId == Model.ItemTypeId)
                        {
                            <option value="@itemTypeId" selected="selected">@itemType</option>
                        }
                        else
                        {
                            <option value="@itemTypeId">@itemType</option>
                        }
                    }
                </select>

            </td>
            </tr>
            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.Content)
                </td>
                <td class="adminData">
                    @Html.TextAreaFor(model => model.Content)
                    @Html.ValidationMessageFor(model => model.Content)
                </td>
            </tr>
               <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.ImageId)
                </td>
                <td class="adminData">

                    <div class="pictureContainer">
                        @Html.EditorFor(model => model.ImageId)
                        @Html.ValidationMessageFor(model => model.ImageId)
                    </div>
                </td>
            </tr>
            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.Seq)
                </td>
                <td class="adminData">
                    @Html.EditorFor(model => model.Seq)
                    @Html.ValidationMessageFor(model => model.Seq)
                </td>
            </tr>
            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.ItemsWide)
                </td>
                <td class="adminData">
                    @Html.EditorFor(model => model.ItemsWide)
                    @Html.ValidationMessageFor(model => model.ItemsWide)
                </td>
            </tr>
            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.ItemsHigh)
                </td>
                <td class="adminData">
                    @Html.EditorFor(model => model.ItemsHigh)
                    @Html.ValidationMessageFor(model => model.ItemsHigh)
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <button type="submit" id="insertGridItem" class="insertGridItem">Insert</button>
                </td>
            </tr>
        </table>

    }
    </div>

Views/MiscGridLayout/Configure.cshtml
@{
    Layout = "";
}
<h1>
    Configuration
</h1>

Views/MiscGridLayout/EditGridItem.cshtml
@model Nop.Plugin.Misc.GridLayout.Models.GridItem
@using Telerik.Web.Mvc.UI;

<div style="height:550px;width:800px;padding:20px;background:#fefefe;">
    <script type="text/javascript">

        function onGridItemUpdateComplete() {

            // resets the recently changed items
            // $(':input').not(':button, :submit, :reset, :hidden').val('');
            $(".edit-grid-item-messages").html("");
            $(".edit-grid-item-messages").append("<strong>Grid item updated</strong><br />");
            var grid = $("#GridItems").data("tGrid");
            grid.rebind();

        }

        function onGridItemUpdateFailure() {
            $(".edit-grid-item-messages").html("");
            $(".edit-grid-item-messages").append("<strong>Please select a grid item to edit and check the values are correct</strong><br />");
        }


        // Return to the normal grid view.
        $(".updateGridItemCancel").on("click", function () {
            var grid = $("#GridItems").data("tGrid");
            grid.rebind();
        });

    </script>
    @using (Ajax.BeginForm("_UpdateGridItem", "GridLayout", new AjaxOptions { OnSuccess = "onGridItemUpdateComplete", OnFailure = "onGridItemUpdateFailure" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <br />
        <h2>Edit Grid Item </h2>
        <div class="edit-grid-item-messages">

        </div>
        <table class="adminContent">
            <tr>
                <td class="adminTitle">
                    <!-- Hidden Id-->
                    <input type="hidden" name="Id" value="@Model.Id" />

                    <!-- Hidden Group Id-->
                    <input type="hidden" name="GridGroupId" value="@Model.GridGroupId" />

                    <!-- Title -->
                    @Html.LabelFor(model => model.Title)
                </td>
                <td class="adminData">
                    @Html.EditorFor(model => model.Title)
                    @Html.ValidationMessageFor(model => model.Title)
                </td>
            </tr>

            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.URL)
                </td>
                <td class="adminData">
                    @Html.EditorFor(model => model.URL)
                    @Html.ValidationMessageFor(model => model.URL)
                </td>
            </tr>
            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.ItemTypeId)
                </td>
                <td class="adminData">
                   @* Look to bring this back on the view model, with more time! *@
                    <select id="ItemTypeId" name="ItemTypeId">
                        @foreach (Nop.Plugin.Misc.GridLayout.Models.GridItemType itemType in Enum.GetValues(typeof(Nop.Plugin.Misc.GridLayout.Models.GridItemType)))
                        {
                            int itemTypeId = (int)itemType;
                            if (itemTypeId == Model.ItemTypeId)
                            {
                                <option value="@itemTypeId" selected="selected">@itemType</option>
                            }
                            else
                            {
                                <option value="@itemTypeId">@itemType</option>
                            }
                        }
                    </select>

                </td>
            </tr>
            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.Content)
                </td>
                <td class="adminData">
                    @Html.TextAreaFor(model => model.Content)
                    @Html.ValidationMessageFor(model => model.Content)
                </td>
            </tr>
               <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.ImageId)
                </td>
                <td class="adminData">

                    <div class="pictureContainer">
                        @Html.EditorFor(model => model.ImageId)
                        @Html.ValidationMessageFor(model => model.ImageId)
                    </div>
                </td>
            </tr>
            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.Seq)
                </td>
                <td class="adminData">
                    @Html.EditorFor(model => model.Seq)
                    @Html.ValidationMessageFor(model => model.Seq)
                </td>
            </tr>
            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.ItemsWide)
                </td>
                <td class="adminData">
                    @Html.EditorFor(model => model.ItemsWide)
                    @Html.ValidationMessageFor(model => model.ItemsWide)
                </td>
            </tr>
            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.ItemsHigh)
                </td>
                <td class="adminData">
                    @Html.EditorFor(model => model.ItemsHigh)
                    @Html.ValidationMessageFor(model => model.ItemsHigh)
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <button type="submit" id="updateGridItem" class="updateGridItem">Update</button>
                </td>
            </tr>
        </table>

    }
    </div>

Views/MiscGridLayout/HasGridLayouts.cshtml
@ViewData["HasAny"]

Views/MiscGridLayout/Index.cshtml
@using Nop.Plugin.Misc.GridLayout.Models
@using Telerik.Web.Mvc.UI;
@{
   Layout = "_AdminLayout";
}

<script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>

<style type="text/css">

    .grid-layout-menu {
        float: left;
    }

    .grid-layout-menu ul {
        margin: 0;
        padding: 0;
        list-style: none;
    }

     .grid-layout-menu li {
            float: left;
            display: inline;
            list-style-type: none;
            margin: 0 3px;
     }

    .grid-layout-menu li a {
        color: #111;
    }

    .btn {
        display: block;
        background: #e9e9e9;
        padding: 5px;
        border: 1px solid #ccc;
    }

    .clear {
        clear: both;
    }

</style>
<h1>
   Grid Layout
</h1>
<br />

<div class="t-widget t-tabstrip t-header" id="GridLayout">
    <ul class="t-reset t-tabstrip-items">
        <li class="t-item t-state-default t-state-active">
            <a class="t-link" href="/Admin/GridLayout/Admin/GridLayout/Index">Layouts</a>
        </li>
        <li class="t-item t-state-default"> 
            <a class="t-link" href="/Admin/GridLayout/Admin/GridAssignment/Index">Page Associations</a>
        </li>
    </ul>
    <div class="t-content t-state-active" id="GridLayout-1" style="display:block">

        <div id="notificationBox"></div>

        <!-- Menu -->
        <div class="grid-layout-menu">
            <ul>
                <li>
                    <a href="/Admin/GridLayout/Admin/GridLayout/Manage/" class="btn">Create Layout</a>
                </li>
            </ul>
        </div>
        <div class="clear"></div>
   
        <br />
        
           @(Html.Telerik().Grid<Nop.Plugin.Misc.GridLayout.Models.GridGroup>()
            .Name("GridGroups")
            .DataBinding(dataBinding => dataBinding.Ajax().Select("_GetAllGridGroups", "GridLayout", new {  }))
            .Columns(columns =>
            {
                columns.Bound(x => x.Title);
                columns.Bound(x => x.Description).Width("200px").Title("Description");
                columns.Bound(x => x.CreatedOn);
                columns.Bound(x => x.ItemsCount).Title("Items");
                columns.Bound(x => x.Id).Width("200px").ClientTemplate("<button class='editGridGroup'>Edit</button><button class='deleteGridGroup'>Delete</button>").Title("Actions");
            }))

            @*@String.Format("{0:d/M/yyyy HH:mm:ss}", gridLayout.GridGroup.CreatedOn)</td>*@

</div>
</div>

<script type="text/javascript">
    
    $(document).ajaxStop(function() {

        //Edit selected grid group
        $(".editGridGroup").on("click", function (e) {
            var masterRow = $(this).parents("tr");
            var dataItem = $('#GridGroups').data('tGrid').dataItem(masterRow);

            e.stopImmediatePropagation();
            e.preventDefault();

            // Use js to redirect.
            window.location = "/Admin/GridLayout/Admin/GridLayout/Manage?Id=" + dataItem['Id'];
        });

        //Delete (Reset styles)
        $(".deleteGridGroup").on("click", function (e) {
            var masterRow = $(this).parents("tr");
            var dataItem = $('#GridGroups').data('tGrid').dataItem(masterRow);

            e.stopImmediatePropagation();
            e.preventDefault();

            if (confirm("Are you sure you wish to delete this layout?. Pages to which this layout has been allocated will no longer be able to display it.")) {
                $.post('@Url.Action("_DeleteGridGroup", "GridLayout")', { id: dataItem['Id'] }).done(function (data) {
                    $("#notificationBox").html("");
                    $("#notificationBox").append("<strong>Grid Group Removed</strong><br />");
                    var grid = $("#GridGroups").data("tGrid");
                    grid.rebind();
                });
            }
        });
    });
  
</script>

Views/MiscGridLayout/PreviewLayout.cshtml
@model Nop.Plugin.Misc.GridLayout.Models.GridGroup

<div style="height:960px;width:1140px;background:#fff;">

    <script type="text/javascript" src="/Plugins/Misc.GridLayout/Content/Scripts/masonry.js"> </script>
    <link href="/Plugins/Misc.GridLayout/Content/Scripts/masonry.css" rel="stylesheet" type="text/css" />

    <script type="text/javascript">

        /* GridGroup     
            Title 
            Description
        */

        /* GridItem
            Title 
            Content
            URL
            Image
            ItemsWide
            ItemsHigh
            Seq
            GridGroupId
         */

        function GridLayout(target)
        {
            var gridGroupId = @Model.Id;
            this.target = $(target);
            this.getGridLayout(gridGroupId);
        }

        GridLayout.prototype.getGridLayout = function (id) {

            var model = { gridGroupId : id };
            var me = this;

            // Get the gridgroups
            $.post('@Url.Action("_GetGridLayout", "GridLayout")', model).done(function (data) {

             
                var html = me.renderGroup(data);
                me.target.html(html);
                
                setTimeout(function() {

                    // now set the masonry business.
                    // initialize
                    me.target.masonry({
                        columnWidth: 145,
                        gutter: 16,
                        itemSelector: '.masonry-item'
                    });

                }, 1000);

            });
        }
 
        GridLayout.prototype.renderGroups = function(data) {
    
            //alert("render groups");
            var groupsLength = data.length;
            var html = "";
    
            for(var i=0; i<groupsLength; i++)
            {
                var gridGroup = data[i];

                // Get the group and pass it to render its items
                html += this.renderGroup(gridGroup);
            }
    
            return html;
        }
         
        GridLayout.prototype.renderGroup = function(data) {
    
            //alert("render group");
            var gridItemsLength = data.Items.length;
            var html = "";

            //html+= data.Title;
            //html+= data.Description;
              
            for (var i = 0; i < gridItemsLength; i++) {
                var gridItem = data.Items[i];
                html+= this.renderGridItem(gridItem);
            }
    
            return html;
        }
      
        GridLayout.prototype.renderGridItem = function(data)
        {
            //alert("render gridItem");
            var typeText = data.TypeText;
            if(typeText != null && typeText !="")
            {
                typeText = typeText.toLowerCase();    
            }

            var html ='<div class="masonry-item w'+data.ItemsWide+' h'+data.ItemsHigh+' '+typeText+'">';
            html+='<a href="'+data.URL+'">';
            if(data.Image != "" && data.Image != null)
            {
                html += '<img src="' + data.Image + '" />';
            }
            html += '<span class="masonry-item-content">';
            if (data.Title != null) {
                html +='<span class="masonry-item-title">'+data.Title+'</span>';
            }
            if (data.Content != null) {
                html +='<span class="masonry-item-desc">'+data.Content+'</span>';
            }
            html += '</span>';

            html+='</a>';
            html+='</div>';
            return html;
        }
         
    var gridLayout = new GridLayout(".masonry-container");

    </script>
 
    <div class="masonry-container" style="padding-top:16px">

        <h1>No grid items found</h1>

    </div>

</div>