3.4/Controllers/GridAssignmentController.cs
using System.Web.Mvc;
using Nop.Web.Framework.Controllers;
using Nop.Plugin.Misc.GridLayout.Models;
using Nop.Core.Data;
using Nop.Services.Catalog;
using Nop.Plugin.Misc.GridLayout.ViewModels;
using System.Collections.Generic;
using Nop.Core.Domain.Catalog;
using System.Linq;
using Nop.Services.Configuration;
using Nop.Services.Media;
using Nop.Web.Models.Catalog;
using Nop.Web.Models.Media;
using Nop.Core.Domain.Media;
using Nop.Services.Localization;
using Telerik.Web.Mvc;
using Nop.Admin.Models.Catalog;
using Nop.Services.Security;
using Nop.Core;
using Nop.Core.Domain;
using Nop.Core.Domain.Common;
using Nop.Admin;
using Nop.Web.Framework;
using System;
using Nop.Plugin.Misc.GridLayout.Services;
using Nop.Plugin.Misc.CategoryRoutes;
using Nop.Plugin.Misc.CategoryRoutes.Services;
using Nop.Plugin.Misc.CategoryRoutes.Models;  // Dependancy on another plugin :(

namespace Nop.Plugin.Misc.GridLayout.Controllers
{

    public class GridAssignmentController : Controller
    {
        private readonly IGridLayoutService _gridLayoutService;
        private readonly ICategoryService _categoryService;
        private readonly GridLayoutSettings _gridLayoutSettings;
        private readonly ISettingService _settingService;
        private readonly IPictureService _pictureService;
        private readonly IProductService _productService;
        private readonly MediaSettings _mediaSettings;
        private readonly ILocalizationService _localizationService;
        private readonly IWorkContext _workContext;
        private readonly IPermissionService _permissionService;
        private readonly AdminAreaSettings _adminAreaSettings;
        private readonly ICategoryRoutesService _categoryRoutesService;

        private readonly string _entityType = "category";


        public GridAssignmentController(ICategoryRoutesService categoryRoutesService, IGridLayoutService gridLayoutService, ICategoryService categoryService, GridLayoutSettings gridLayoutSettings, ISettingService settingService, IPictureService pictureService, IProductService productService, MediaSettings mediaSettings, ILocalizationService localizationService, IPermissionService permissionService, IWorkContext workContext, AdminAreaSettings adminAreaSettings)
        {
            _gridLayoutService = gridLayoutService;
            _gridLayoutSettings = gridLayoutSettings;
            _categoryService = categoryService;
            _settingService = settingService;
            _pictureService = pictureService;
            _productService = productService;
            _mediaSettings = mediaSettings;
          
            _localizationService = localizationService;
            _workContext = workContext;
            _permissionService = permissionService;
            _adminAreaSettings = adminAreaSettings;
            _categoryRoutesService = categoryRoutesService;
        }

        [AdminAuthorize]
        [HttpGet]
        public ActionResult Index()
        {
            return View("~/Plugins/Misc.GridLayout/Views/MiscGridAssignment/Index.cshtml");
        }

        #region Ajax Methods

        /// <summary>
        /// Get Grid Layouts for a specified category / product
        /// </summary>
        /// <param name="gridItem"></param>
        /// <returns></returns>
        [GridAction]
        [AdminAuthorize]
        public JsonResult _GetAllGridGroupToPage()
        {
            return Json(this.PrepareGridGroupToPageViewModel(this._gridLayoutService.GetAllGridGroupToPage()));
        }

        /// <summary>
        /// Prepare Grid Group To Page View Model
        /// TODO : 
        /// Make Stored proceedure do this for us if this takes too long!
        /// </summary>
        /// <returns></returns>
        private IList<GridGroupToPageViewModel> PrepareGridGroupToPageViewModel(IList<GridGroupToPage> gridGroupsToPage)
        {
            IList<GridGroupToPageViewModel> gridGroupsToPageViewModels = new List<GridGroupToPageViewModel>();

            if (gridGroupsToPage != null)
            {
                foreach (var gridGroupToPage in gridGroupsToPage)
                {
                    GridGroupToPageViewModel gridGroupToPageViewModel = new GridGroupToPageViewModel();

                    if (!String.IsNullOrEmpty(gridGroupToPage.EntityType))
                    {
                        if (gridGroupToPage.EntityType.ToLower() == _entityType && gridGroupToPage.EntityId > 0)
                        {
                            Category category = _categoryService.GetCategoryById(gridGroupToPage.EntityId);
                           
                            if (category != null)
                            {
                                // Set the name
                                gridGroupToPageViewModel.EntityName = category.Name;

                                EntityRouteURL routeURL = this._categoryRoutesService.GetCategoryURLById(category.Id);
                                if (routeURL != null)
                                {
                                    // Set the link
                                    gridGroupToPageViewModel.Link = routeURL.Route;
                                }
                            }
                        }
                    }

                    // get the group
                    if (gridGroupToPage.GridGroup != null)
                    {
                        gridGroupToPageViewModel.GridGroupTitle = gridGroupToPage.GridGroup.Title;
                        gridGroupToPageViewModel.GridGroupShortCode = gridGroupToPage.GridGroup.ShortCode;
                    }
                    else
                    {
                        GridGroup gridGroup = _gridLayoutService.GetGridGroupById(gridGroupToPage.GridGroupId);
                        if (gridGroup != null)
                        {
                            gridGroupToPageViewModel.GridGroupTitle = gridGroup.Title;
                            gridGroupToPageViewModel.GridGroupShortCode = gridGroup.ShortCode;
                        }
                    }

                    gridGroupToPageViewModel.IsActive = gridGroupToPage.IsActive;
                    gridGroupToPageViewModel.Id = gridGroupToPage.Id;
                    gridGroupToPageViewModel.CreatedOn = gridGroupToPage.CreatedOn;
                 
                    // Add this to the list!
                    gridGroupsToPageViewModels.Add(gridGroupToPageViewModel);
                }
            }

            return gridGroupsToPageViewModels;
        }

        /// <summary>
        /// Get Grid Group to Page
        /// to add .... this is a post as it is being called via ajax 
        /// and it didnt seem to like gets.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [AdminAuthorize]
        public ActionResult _GetGridGroupToPage()
        {
            GridGroupToPage model = new GridGroupToPage(this._entityType);

            // For now set the entity type to be "Category" this follows the nopcommerce convention.
       
            // Create a GridGroupToPageViewModel
            GridGroupToPageDetailViewModel viewModel = new GridGroupToPageDetailViewModel();
            viewModel.GridGroupToPage = model;

            // Add Available Categories in drop down.
            viewModel.Categories = new List<SelectListItem>();
            viewModel.Categories.Add(new SelectListItem() { Text = "Choose a Category", Value = "0" });
            foreach (var category in _categoryService.GetAllCategories("", 0, int.MaxValue, true))
                viewModel.Categories.Add(new SelectListItem() { Text = category.Name, Value = category.Id.ToString() });

            // Add Available Grid Groups to the drop down - user their name and id.
            viewModel.GridGroups = new List<SelectListItem>();
            viewModel.GridGroups.Add(new SelectListItem() { Text = "Choose a Grid Layout", Value = "0" });
            foreach (var gridGroup in _gridLayoutService.GetAllGridGroups())
                viewModel.GridGroups.Add(new SelectListItem() { Text = gridGroup.Title, Value = gridGroup.Id.ToString() });

            return View("~/Plugins/Misc.GridLayout/Views/MiscGridAssignment/AddGridGroupToPage.cshtml", viewModel);
        }

        /// <summary>
        /// Prepare Grid Group To Page Model
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        private GridGroupToPageDetailViewModel PrepareGridGroupToPageDetailViewModel(GridGroupToPage model)
        {
            GridGroupToPageDetailViewModel viewModel = new GridGroupToPageDetailViewModel();

            // Assign it back to the viewmodel.
            viewModel.GridGroupToPage = model;

            // Add Available Categories in drop down.
            viewModel.Categories = new List<SelectListItem>();
            viewModel.Categories.Add(new SelectListItem() { Text = "Choose a Category", Value = "0" });
            foreach (var category in _categoryService.GetAllCategories("", 0, int.MaxValue, true))
            {
           
                if (viewModel.GridGroupToPage != null && category.Id == viewModel.GridGroupToPage.EntityId)
                {
                    viewModel.Categories.Add(new SelectListItem() { Text = category.Name, Value = category.Id.ToString(), Selected = true });
                }
                else
                {
                    viewModel.Categories.Add(new SelectListItem() { Text = category.Name, Value = category.Id.ToString() });
                }
            }

            // Add Available Grid Groups to the drop down - user their name and id.
            viewModel.GridGroups = new List<SelectListItem>();
            viewModel.GridGroups.Add(new SelectListItem() { Text = "Choose a Grid Layout", Value = "0" });
            foreach (var gridGroup in _gridLayoutService.GetAllGridGroups())
            {

3.4/Views/MiscGridAssignment/AddGridGroupToPage.cshtml
@model Nop.Plugin.Misc.GridLayout.ViewModels.GridGroupToPageDetailViewModel
@using Telerik.Web.Mvc.UI;

<div style="height:350px;width:800px;padding:20px;background:#fefefe;">
    <script type="text/javascript">

        function onGridGroupToPageInsertComplete() {
            // resets the recently changed items
            // $(':input').not(':button, :submit, :reset, :hidden').val('');
            jQuery(".insert-grid-grouptopage-messages").html("");
            jQuery(".insert-grid-grouptopage-messages").append("<strong>Grid group to page inserted</strong><br />");
            var grid = $("#GridGroupToPage").data("tGrid");
            grid.rebind();

        }

        function onGridGroupToPageInsertFailure() {
            jQuery(".insert-grid-grouptopage-messages").html("");
            jQuery(".insert-grid-grouptopage-messages").append("<strong>There were issues inserting the grid group to page mapping, please check the values are correct</strong><br />");
        }

        /*
        $(".updateGridItem").on("click", function () {
            var grid = $("#GridItems").data("tGrid");
            grid.rebind();
        });
        */

        // Return to the normal grid view.
        jQuery(".insertGridGroupToPageCancel").on("click", function () {
            var grid = jQuery("#GridGroupToPage").data("tGrid");
            grid.rebind();
        });

    </script>
    @using (Ajax.BeginForm("_InsertGridGroupToPage", "GridAssignment", new AjaxOptions { OnSuccess = "onGridGroupToPageInsertComplete", OnFailure = "onGridGroupToPageInsertFailure" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <br />
        <h2>Create - Layout to Page Association  </h2>
        <div class="insert-grid-grouptopage-messages">

        </div>
        <br />
        <table class="adminContent">
            <tr>
                <td class="adminTitle">

                    <input type="hidden" name="GridGroupToPage.Id" value="@Model.GridGroupToPage.Id" />
                    <input type="hidden" name="GridGroupToPage.EntityType" value="@Model.GridGroupToPage.EntityType" /> 

                    @Html.LabelFor(model => model.GridGroupToPage.IsActive)

                </td>
                <td class="adminData">
                    @Html.EditorFor(model => model.GridGroupToPage.IsActive)
                    @Html.ValidationMessageFor(model => model.GridGroupToPage.IsActive)
                </td>
            </tr>

            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.Categories):
                </td>
                <td class="adminData">
                    @Html.DropDownList("GridGroupToPage.EntityId", Model.Categories)
                </td>
            </tr>

            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.GridGroups):
                </td>
                <td class="adminData">
                    @Html.DropDownList("GridGroupToPage.GridGroupId", Model.GridGroups)
                </td>
            </tr>
            
            <tr>
                <td colspan="2">
                    <button type="submit" id="insertGridGroupToPage" class="insertGridGroupToPage">Insert</button>
                </td>
            </tr>
        </table>

    }
</div>

3.4/Views/MiscGridAssignment/EditGridGroupToPage.cshtml
@model Nop.Plugin.Misc.GridLayout.ViewModels.GridGroupToPageDetailViewModel
@using Telerik.Web.Mvc.UI;

<div style="height:350px;width:800px;padding:20px;background:#fefefe;">
    <script type="text/javascript">

        function onGridGroupToPageUpdateComplete() {
            // resets the recently changed items
            // $(':input').not(':button, :submit, :reset, :hidden').val('');
            jQuery(".edit-grid-grouptopage-messages").html("");
            jQuery(".edit-grid-grouptopage-messages").append("<strong>Grid group to page updated</strong><br />");
            var grid = $("#GridGroupToPage").data("tGrid");
            grid.rebind();

        }

        function onGridGroupToPageUpdateFailure() {
            jQuery(".edit-grid-grouptopage-messages").html("");
            jQuery(".edit-grid-grouptopage-messages").append("<strong>There were issues updating the grid group to page mapping, please check the values are correct</strong><br />");
        }

        // Return to the normal grid view.
        jQuery(".updateGridGroupToPageCancel").on("click", function () {
            var grid = jQuery("#GridGroupToPage").data("tGrid");
            grid.rebind();
        });

    </script>
    @using (Ajax.BeginForm("_UpdateGridGroupToPage", "GridAssignment", new AjaxOptions { OnSuccess = "onGridGroupToPageUpdateComplete", OnFailure = "onGridGroupToPageUpdateFailure" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <br />
        <h2>Edit - Layout to Page Association </h2>
        <div class="edit-grid-grouptopage-messages">

        </div>
        <br />
        <table class="adminContent">
            <tr>
                <td class="adminTitle">
                    <!-- Hidden Id, not populate yet as we are new.-->
                    <input type="hidden" name="GridGroupToPage.Id" value="@Model.GridGroupToPage.Id" />
                    <input type="hidden" name="GridGroupToPage.EntityType" value="@Model.GridGroupToPage.EntityType" /> 

                    @Html.LabelFor(model => model.GridGroupToPage.IsActive)

                </td>
                <td class="adminData">
                    @Html.EditorFor(model => model.GridGroupToPage.IsActive)
                    @Html.ValidationMessageFor(model => model.GridGroupToPage.IsActive)
                </td>
            </tr>

            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.Categories):
                </td>
                <td class="adminData">
                    @Html.DropDownList("GridGroupToPage.EntityId", Model.Categories)
                </td>
            </tr>

            <tr>
                <td class="adminTitle">
                    @Html.LabelFor(model => model.GridGroups):
                </td>
                <td class="adminData">
                    @Html.DropDownList("GridGroupToPage.GridGroupId", Model.GridGroups)
                </td>
            </tr>
            
            <tr>
                <td colspan="2">
                    <button type="submit" id="updateGridGroupToPage" class="updateGridGroupToPage">Update</button>
                </td>
            </tr>
        </table>

    }
</div>

3.4/Views/MiscGridAssignment/Index.cshtml
@using Nop.Plugin.Misc.GridLayout.Models
@using Telerik.Web.Mvc.UI;
@{
    Layout = "_AdminLayout";
}

<script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>

<link rel="stylesheet" href="/Content/fancybox/jquery.fancybox-1.3.4.css" />
<script src="/Scripts/jquery.fancybox-1.3.4.pack.js" type="text/javascript"></script>

<style type="text/css">
    .btn {
        display: block;
        background: #e9e9e9;
        padding: 5px;
        border: 1px solid #ccc;
    }

    .grid-layout-menu {
        float: left;

    }

    .grid-layout-menu ul{
        margin:0;
        padding:0;
        list-style:none;
    }

    .grid-layout-menu li {
        float: left;
        display: inline;
        list-style-type: none;
        margin: 0 3px;
    }

    .grid-layout-menu li a {
        color: #111;
    }

    .clear {
        clear: both;
    }
</style>

<h1>
    Grid Layout
</h1>
<br />

<div class="t-widget t-tabstrip t-header" id="GridLayout">
    <ul class="t-reset t-tabstrip-items">
        <li class="t-item t-state-default">
            <a class="t-link" href="/Admin/GridLayout/Admin/GridLayout/Index">Layouts</a>
        </li>
        <li class="t-item t-state-default t-state-active">
            <a class="t-link" href="/Admin/GridLayout/Admin/GridAssignment/Index">Page Associations</a>
        </li>
    </ul>
    <div class="t-content t-state-active" id="GridLayout-1" style="display:block">
     
        <!-- Menu -->
        <div class="grid-layout-menu">
            <ul>
                <li>
                    <a href="#" class="addGridGroupToPage btn"> Create layout to page association</a>
                 </li>
            </ul>
        </div>
        <div class="clear"></div>
        <p>Once a layout has been created it needs to be associated with a page in order for it to appear in the customer visible part of the store. <br />
         A single layout can be associated to multiple pages and can be made to show / hide by setting its active state. <br />
         Once a layout has been associated with a page, deleting the layout will also delete the page association.
        </p>
        <br />

        <div id="notificationBox">

        </div>

        <br />

        <!-- Use telerik control... -->
        @(Html.Telerik().Grid<Nop.Plugin.Misc.GridLayout.ViewModels.GridGroupToPageViewModel>()
                .Name("GridGroupToPage")
                .DataBinding(dataBinding => dataBinding.Ajax().Select("_GetAllGridGroupToPage", "GridAssignment", new { }))
                .Columns(columns =>
                {
                    columns.Bound(x => x.IsActive);
                    columns.Bound(x => x.GridGroupTitle).Title("Layout Name");
                    columns.Bound(x => x.EntityName).Title("Category Name");
                    columns.Bound(x => x.Link);
                    columns.Bound(x => x.GridGroupShortCode).Title("Short Code");
                    columns.Bound(x => x.CreatedOn).Title("Created On");
                    columns.Bound(x => x.Id).Width("200px").ClientTemplate("<button class='editGridGroupToPage'>Edit</button><button class='deleteGridGroupToPage'>Delete</button>").Title("Actions");
                }))
    </div>
</div>

<script type="text/javascript">

    $(document).ajaxStop(function () {

        // Add Grid Group to page
        $(".addGridGroupToPage").on("click", function () {

            var model = {};
            $.post('@Url.Action("_GetGridGroupToPage","GridAssignment")', model).done(function (data) {

                $.fancybox({
                    'padding': 0,
                    'autoScale': true,
                    'transitionIn': 'none',
                    'transitionOut': 'none',
                    'width': 700,
                    'height': 700,
                    'content': data
                });
            });
        });

        //Edit Grid Group to page
        $(".editGridGroupToPage").on("click", function () {

            var masterRow = $(this).parents("tr");
            var dataItem = $('#GridGroupToPage').data('tGrid').dataItem(masterRow);

            // Construct object to send
            var model = { id: dataItem['Id'] };

            $.post('@Url.Action("_GetGridGroupToPageById", "GridAssignment")', model).done(function (data) {

                $.fancybox({
                    'padding': 0,
                    'autoScale': true,
                    'transitionIn': 'none',
                    'transitionOut': 'none',
                    'width': 700,
                    'height': 700,
                    'content': data
                });
            });
        });

        //Delete (Reset styles)
        $(".deleteGridGroupToPage").on("click", function (e) {
            var masterRow = $(this).parents("tr");
            var dataItem = $('#GridGroupToPage').data('tGrid').dataItem(masterRow);

            e.stopImmediatePropagation();
            e.preventDefault();

            if (confirm("Are you sure you wish to delete this layout to page allocation?")) {
                $.post('@Url.Action("_DeleteGridGroupToPage", "GridAssignment")', { id: dataItem['Id'] }).done(function (data) {
                    $("#notificationBox").html("");
                    $("#notificationBox").append("<strong>Grid Group to page removed</strong><br />");
                    var grid = $("#GridGroupToPage").data("tGrid");
                    grid.rebind();
                });
            }
        });
    });
</script>